ThatConference/thatconference.com

src/_components/notifications/CreateProfile.svelte, src/lib/formSchemas/emergencyContact.js, src/lib/formSchemas/primaryProfile.js, src/routes/(admin my)/my/profiles/primary/+page.server.js, src/routes/(admin my)/my/profiles/primary/+page.svelte, src/routes/(admin my)/my/profiles/primary/profileForm.svelte, src/routes/(root)/verify-account/+page.svelte
* removes refine method from the schema.
* adds the validate check into the submit action
* Sets error if the slug is taken from the submit action
* clears errors on input change
fixes #18 
fixes #19
=> fix: profileSlug validation

src/routes/(admin my)/my/favorites/+page.svelte
Fix typo in /activities url for my favorites download
=> fix: typo in favorites download

.github/workflows/release-success.yml, package.json, src/_elements/links/Standard.svelte, src/lib/formSchemas/sharedProfile.js, src/routes/(admin my)/my/profiles/shared/sharedProfileForm.svelte, src/routes/(root)/orders/_components/_Cart.svelte, src/routes/(root)/orders/canceled/+page.svelte, src/routes/(root)/orders/success/+layout.svelte, src/routes/(root)/orders/success/+page.svelte, src/routes/(root)/orders/success/claim-ticket/+page.svelte, src/routes/(root)/support/staying-up-to-date/+page.svelte, src/routes/(root)/support/transfer-a-ticket/+page.svelte
- refactor order success page to improve message and add latest THAT offerings
- Remove bing update ping from `release-success` as it's no longer supported by bing
- fixed shared profile phone number field formatting
- when phone number `null` from datastore error calling `event.target.value.replace()` on line 39
- API will only accept a valid phone number or a null value, updated so an empty phone number is a null value. Adjusted Zod accordingly.
- Updated Zod rules to allow RegEx approved phone number or null. Optional doesn't work in the case with a regex. It is recommended to use `z.union()` or `.or()` in this case.
- success page on ticket purchase: `/orders/success?EL=tx&M=0&B=0&TL=at`
- success page on ticket purchase w/ bulk: `/orders/success?EL=tx&M=0&B=4&TL=at`
- success page on …
=> Refactor order success page

package.json, src/lib/config.public.js, src/routes/(admin sponsor)/sponsor-admin/leads/+page.js, src/routes/(admin sponsor)/sponsor-admin/leads/+page.svelte, src/routes/(admin sponsor)/sponsor-admin/leads/[eventId]/+page.svelte, src/routes/(root)/support/sponsors/forms/+page.svelte
- refactor: leads for thatconference.com, correct referenced paths (/sponsor-admin)
- refactor: move hard-coded event ids to public config
- feat: add event selection at /leads root
- validated all links in /support/sponsor/forms fix some styling
=> get leads working on thatconference.com

package.json, src/routes/(that conference online)/[event]/[date]/+layout.js, src/routes/(that conference online)/_components/EventTicket.svelte, src/routes/(that conference online)/_components/OnlineHero.svelte, src/routes/(that conferences)/+layout.js
- fix issue where routes to non-existent events threw a 500 error. The routes respond appropriately.
=> fix: routes to non-existend events

package.json, src/hooks.server.js
- Fixes validation of email verification on new accounts.
=> fix: check for verified emails on auth'd paths

__MIGRATION_TBD__/__events copy__/(thatConferences)/_components/nav/NavHat.svelte, package.json, src/_components/navigation/thatConference/NavHat.svelte, src/lib/stores/favorites.js
fixes #118 
401 was being thrown as we we're checking for profile which was an empty object and it should have been checking for isAuthenticated.
=> fix: http 401 on favorites

package.json, src/_components/activities/ActivityDetails.svelte, src/_components/cta/_HomePageCFP.svelte, src/_components/cta/_TicketsOnSale.svelte, src/_components/navigation/thatConference/NavHat.svelte, src/routes/(redirects)/family/+page.js, src/routes/(that conference online)/[event]/[date]/+page.svelte, src/routes/(that conferences)/tx/[year]/+page.svelte, src/routes/(that conferences)/tx/[year]/_components/CamperTickets.svelte, src/routes/(that conferences)/tx/[year]/schedule/+page.svelte, src/routes/(that conferences)/tx/[year]/sponsors/+page.svelte, src/routes/(that conferences)/tx/[year]/tickets/+page.svelte, src/routes/(that conferences)/wi/[year]/_components/CamperTickets.svelte
- fix references of `/events/{slug}` to `/{slug}` 
fixes #93
=> fix: references of /events/{slug} to /{slug}

package.json, src/routes/(redirects)/membership/+page.js, src/routes/(root)/_root/components/ctaMembership.svelte
- add temporary redirect for `/membership` to that.us
fixes #107
=> refactor: /membership route to that.us in the short term

package.json, src/_components/activities/ActivityDetails.svelte, src/_components/cta/_HomePageCFP.svelte, src/_components/cta/_TicketsOnSale.svelte, src/_components/navigation/thatConference/NavHat.svelte, src/routes/(redirects)/family/+page.js, src/routes/(redirects)/membership/+page.js, src/routes/(root)/_root/components/ctaMembership.svelte, src/routes/(that conference online)/[event]/[date]/+page.svelte, src/routes/(that conferences)/tx/[year]/+page.svelte, src/routes/(that conferences)/tx/[year]/_components/CamperTickets.svelte, src/routes/(that conferences)/tx/[year]/schedule/+page.svelte, src/routes/(that conferences)/tx/[year]/sponsors/+page.svelte, src/routes/(that conferences)/tx/[year]/tickets/+page.svelte, src/routes/(that conferences)/wi/[year]/_components/CamperTickets.svelte
includes pr #122 
includes pr #121
=> Promote Next/feature to Production

package-lock.json, package.json, src/_dataSources/api.that.tech/events/queries.js, src/lib/claimTicket/config.js, src/lib/claimTicket/machine.js, src/routes/(root)/orders/_components/_ClaimCart.svelte, src/routes/(root)/orders/success/expo-hall-ticket/+page.svelte, src/routes/(root)/support/sponsors/expo-hall/+page.svelte, src/routes/(that conference online)/[event]/[date]/+page.svelte, src/routes/(that conference online)/_components/EventTicket.svelte
- feat: specific landing page for claim ticket type
- refactor: ticket name used in cart
note: We may want to refresh copy on claim-ticket success page
=> Specific success page for claim ticket type

package.json, src/routes/(admin my)/my/network/sponsors/+page.svelte
fix the issue in my network sponsors list where partner contact is null.
Partner contact is null when the connection is created by the member. 
fixes: https://that-conference.sentry.io/issues/4636978875/?alert_rule_id=14721499&alert_type=issue&environment=production&notification_uuid=720cdd00-1ea8-4539-88bd-df0325997dc3&project=4504617287417856&referrer=slack
=> fix: issue where partner contact is null

src/routes/(that conferences)/online/[state]/[year]/sponsors/+page.server.js, src/routes/(that conferences)/online/[state]/[year]/sponsors/+page.svelte
Server load was grabbing the wrong event slug to load sponsors. Also adds the additional tier of sponsors.
=> fixes: incorrect sponsors

package.json, src/routes/(that conferences)/tx/[year]/speakers/+page.js, src/routes/(that conferences)/wi/[year]/speakers/+page.js
filter out duplicate speakers in list and added that to the wi route too
=> fix: duplicate speakers in list

package.json, src/_components/activities/Card.svelte, src/_components/activities/List.svelte
Session cards has listed camp counselor on the cards which is no longer relevant. Now family track is shown instead.
=> session card callout

src/routes/(that conferences)/online/_components/Schedule.svelte, src/routes/(that conferences)/online/_components/schedule/List.svelte
=> chore: schedule update

src/_components/activities/List.svelte
looks at the session status before adding keynotes to the grid
=> fix - cancelled keynotes

src/routes/(that conferences)/_components/LinkDrawer.svelte
fixed up spacing on a mobile device
=> junk drawer spacing

src/routes/(that conferences)/_components/LinkDrawer.svelte
Junk Drawer wasn't scrolling with bigger text.
=> adding scrolling to junk draw

src/routes/(root)/_root/components/hero.svelte, src/routes/(root)/support/travel/wi/+page.svelte, src/routes/+layout.svelte
prose was overriding button styles.
=> ui display bug

src/_dataSources/api.that.tech/events/queries.js
the page size on the event query was too small.
=> updated page size on query
