- package.json
> chore: updating stuff to allow new deploy

- package-lock.json
- src/_utils/ical.js
- src/_utils/seo/metaTags.js
- src/routes/+layout.js
- src/routes/+layout.server.js
- src/routes/support/transfer-a-ticket/+page.svelte
- src/routes/support/travel/+page.svelte
- src/routes/support/travel/tx/+page.svelte
- src/routes/support/travel/wi/+page.svelte
Working through issues logging in to site at feature
All env's validated
> fix: tweaking stuff for feature login and other references

- package.json
- src/routes/events/(thatConferences)/wi/[year]/tickets/_components/Families.svelte
> feat: add pig roast only ticket. fix other family ticket copy

- package.json
- src/routes/events/(thatConferences)/tx/[year]/tickets/_components/Families.svelte
- src/routes/events/(thatConferences)/wi/[year]/tickets/_components/Families.svelte
> Next/feature promoted to main 

- src/routes/(admin my)/my/profiles/emergency-contact/emergencyContactForm.svelte
Clears the server error on input.
> fix: clear error message on input

- src/lib/config.public.js
> fix: passkey properties were wrong for current event

- src/routes/+layout.svelte
> fix: closes #46

- src/routes/(admin my)/my/profiles/+layout.svelte
> Fixes Isses #41

- src/_components/navigation/thatConference/MobileEventNav.svelte
> fix: event link on mobile drop down menu

- .github/workflows/release-success.yml
- package.json
Updates CloudFlare references to purge CloudFlare on deployment to production
New secrets added to this repo's local secrets for the values.
> fix: action to purge cloudflare on deploy

- package.json
- src/routes/(root)/orders/success/claim-ticket/+page.svelte
Update sponsor meeting reference in claim ticket success page.
> chore: update sponsor meeting time on order success

- src/_components/activities/List.svelte
- src/app.html
- src/routes/+layout.svelte
* fixes schedule date not sticking
* changes invalid date -> unscheduled
> fix: schedule headers

- package.json
- src/_components/activities/List.svelte
- src/app.html
- src/routes/+layout.svelte
fix: schedule headers and how unscheduled sessions look on /schedule
> promote Next/feature to production

- package.json
- src/_components/activities/List.svelte
- fix: regression from thatconference/that.us#1451: broken track filters (professional, family)
- fix: community filter
> fix session list filter

- package.json
- src/routes/(admin my)/my/profiles/emergency-contact/emergencyContactForm.svelte
- src/routes/(admin my)/my/profiles/public/PublicProfileForm.svelte
- src/routes/(admin my)/my/profiles/shared/sharedProfileForm.svelte
> refactor: scrollto on save

- package.json
- src/_components/newsletter/HubspotForm.svelte
- src/routes/(admin my)/my/profiles/emergency-contact/emergencyContactForm.svelte
- src/routes/(admin my)/my/profiles/primary/profileForm.svelte
- src/routes/(admin my)/my/profiles/public/PublicProfileForm.svelte
- src/routes/(admin my)/my/profiles/shared/sharedProfileForm.svelte
enables form shapshots https://kit.svelte.dev/docs/snapshots making one live easier.
> refactor: adding snapshots to forms

- package.json
- vercel.json
-Add basic security headers to vercel.json
> Add basic security headers

- package.json
- src/routes/(root)/support/sponsors/forms/+page.svelte
Fix sponsor links in sponsor resource page
> fix: sponsor links on sponsor resource form

- src/_dataSources/api.that.tech/events/queries.js
- src/routes/(admin my)/my/profiles/primary/profileForm.svelte
- src/routes/(root)/support/convince-your-boss/+page.js
- src/routes/(root)/support/convince-your-boss/+page.svelte
- src/routes/(root)/support/convince-your-boss/_components/EventLink.svelte
Adds draft convince you boss page at `/support/convince-your-boss`
Preview at: https://thatconference-com-git-feat-convince-your-boss-that-conference.vercel.app/support/convince-your-boss
Only rough styling done.
> feat: add draft convince your boss page

- src/app.html
- src/lib/tagEvent.js
- static/sitemap.xml
Removing Google Analytics in favor of Vercel, looking at plausible.
> Chore: updating sitemap and analytics

- package-lock.json
- package.json
- src/_components/navigation/default/Base.svelte
- src/_elements/links/Standard.svelte
- src/lib/config.public.js
- src/routes/(admin my)/my/profiles/public/PublicProfileForm.svelte
- src/routes/(root)/blog/+layout.js
- src/routes/(root)/blog/+page.js
- src/routes/(root)/blog/+page.svelte
- src/routes/(root)/blog/[article]/+page.js
- src/routes/(root)/blog/[article]/+page.svelte
- src/routes/(root)/blog/components/ArticleCard.svelte
> feat: adds blog

- package.json
- src/_components/footer/links.js
- src/_components/navigation/default/Base.svelte
- src/_components/navigation/default/links.js
> fix: links

- .husky/commit-msg
- .husky/pre-commit
- commitlint.config.cjs
- package-lock.json
- package.json
- src/routes/(that conferences)/tx/[year]/schedule/+page.svelte
date has to shift forward, this is accounting for those date changes.
> Event Date Changes References

- src/_components/members/MemberConnecting.svelte
- src/_elements/links/Standard.svelte
- src/routes/(root)/members/_components/hero.svelte
When a user is logged out we now add a fake button to take you to login, then redirect back.
> adds connect button on member page

- src/routes/(root)/login/+server.js
- src/routes/(root)/sponsors/_components/_Hero.svelte
adds fake button to sponsors page that will log you in and redirect back
> adds connect button to sponsors page

- src/_components/navigation/_components/NavLink.svelte
- src/_components/navigation/thatConference/MobileEventNav.svelte
Fixes the nav for THAT Conference event pages as it wouldn't close on click
> closes mobile menu on click

- src/_dataSources/api.that.tech/admin/events/mutations.js
- src/_dataSources/api.that.tech/admin/events/queries.js
- src/lib/formSchemas/event.js
- src/routes/(admin)/admin/events/+page.server.js
- src/routes/(admin)/admin/events/+page.svelte
- src/routes/(admin)/admin/events/[id]/edit/+layout.svelte
- src/routes/(admin)/admin/events/[id]/edit/+page.server.js
- src/routes/(admin)/admin/events/[id]/edit/+page.svelte
- src/routes/(admin)/admin/events/_components/EventForm.svelte
- src/routes/(admin)/admin/events/_components/InputBoolean.svelte
- src/routes/(admin)/admin/events/_components/InputDateTime.svelte
- src/routes/(admin)/admin/events/_components/InputText.svelte
- src/routes/(admin)/admin/events/_components/InputTextArea.svelte
- src/routes/(admin)/admin/events/create/+layout.svelte
- src/routes/(admin)/admin/events/create/+page.server.js
- src/routes/(admin)/admin/events/create/+page.svelte
reworks the admin section of the site
adds event listing
adds the ability to create an event
adds the ability to edit an event
add the order listing
reworks where checkin lives
updates security checks for all
adds unit testing
> admin pages for events

- src/_components/EventPicker.svelte
- src/_components/cta/_CallForSpeakers.svelte
- src/_components/navigation/default/Base.svelte
- src/_components/navigation/thatConferenceLive/NavHat.svelte
- src/routes/(root)/_root/components/hero.svelte
- src/routes/(that conferences)/_components/attendees/Hero.svelte
- src/routes/(that conferences)/_components/schedule/Hero.svelte
- src/routes/(that conferences)/_components/speakers/Hero.svelte
- src/routes/(that conferences)/_components/sponsors/Hero.svelte
- src/routes/(that conferences)/online/[state]/[year]/attendees/+page.svelte
- src/routes/(that conferences)/online/[state]/[year]/schedule/+page.svelte
- src/routes/(that conferences)/online/[state]/[year]/speakers/+page.svelte
- src/routes/(that conferences)/online/[state]/[year]/sponsors/+page.svelte
- src/routes/(that conferences)/online/_components/Hero.svelte
Updates overall navigation items
* link in the nav hat
* adds online to the event picker
* adds button to the root hero
* updates venue in the online hero sub pages
> navigation updates

- src/routes/(root)/orders/success/online-ticket/+page.svelte
- src/routes/+layout.svelte
creates the success page for that online ticket holders will be redirected too after checkout.
> feat: adds success page for online

- src/routes/(root)/orders/success/+layout.svelte
- src/routes/(root)/orders/success/+page.svelte
- src/routes/(root)/orders/success/claim-ticket/+page.svelte
Online success page copy updated
cart loaded on page.svelte rather than layout.svelte so it load everytime.
> fix: copy on online success page

- src/routes/(root)/signup/+page.svelte
Updates signup copy to be a bit more clear as to each step in the process.
> enhancement: updates signup copy

- src/_dataSources/api.that.tech/admin/orders/queries.js
- src/routes/(admin)/admin/events/[id]/orders/+page.svelte
adds a detail line to an order line.
> enhancement: admin/orders

- src/_components/activities/List.svelte
reorders the unscheduled sessions to the bottom of the stack
> fix: unscheduled session placement

- src/routes/(that conferences)/tx/[year]/speakers/+page.js
filters out the speakers who were accepted but cancelled.
> fix: cancelled speakers

- package.json
- src/_components/activities/List.svelte
array was coming up empty, so now we check
> fix: dayofyear

- package.json
- src/_components/activities/ActivityDetails.svelte
- src/_components/activities/Card.svelte
- src/routes/(admin my)/my/submissions/_components/submission.svelte
until the CRUD sessions form is brought over this redirects back to that.us
> fix: session edit link

- src/_components/numberPad/Panel.svelte
fixes the row layout for the button panel.
> fix: panel rows

- src/routes/(that conferences)/tx/[year]/schedule/+page.server.js
- src/routes/(that conferences)/tx/[year]/schedule/+page.svelte
Family Filter wasn't added to the texas event route.
> fix: family filter

- src/_dataSources/api.that.tech/sessions.js
- src/hooks.client.js
- src/hooks.server.js
disable sentry's sampling as we've popped the cap.
> chore: disable sampling

- package.json
- src/routes/(event support)/signs/+page.svelte
Fix /signs page when there are no sponsors at presented levels.
> fix: tv/signs page to handle no sponsers at a level

- src/routes/(that conferences)/+layout.svelte
- src/routes/(that conferences)/_components/LinkDrawer.svelte
Introduced a drawer for quick links. this is only for the event pages.
> adds event drawer

- src/routes/(that conferences)/_components/Keynoters.svelte
the current keynote component wasn't checking for the status of the keynoter. so if they had cancelled they would still show.
> check keynoter status

- src/routes/(that conferences)/online/[state]/[year]/+page.svelte
- src/routes/(that conferences)/online/_components/Live.svelte
Adding the embed section for the live stream
> adding streamyard embed

- src/routes/(that conferences)/+layout.svelte
Quick menu was showing on all screen sizes. it's now restricted to just mobile views.
> hide quick menu

- src/lib/config.public.js
> updating passkey links

- src/routes/(that conferences)/_components/Keynoters.svelte
the image masks needed to be set on the keynoters hero images
> updates keynote image masks

- src/routes/(admin my)/my/profiles/public/PublicProfileForm.svelte
updated accepts to all image types
> update image accepts on profile

- src/lib/config.public.js
- src/routes/(root)/speakers/_components/formSections/CampsiteComps.svelte
the room compensentaion was hardcoded and now it's based on a config.
> room kickback updated in speaker accept

- src/_dataSources/api.that.tech/me/favorites/queries.js
- src/routes/(admin my)/my/favorites/+page.svelte
just added the short and long description to the csv exporter.
> adding description to csv export

- package-lock.json
- package.json
sentry version were out of sync
> bumping sentry package

- src/routes/(root)/orders/_components/_Cart.svelte
- src/routes/+layout.js
configure scope is no longer, updating api calls.
> updating sentry api calls

- src/routes/(redirects)/online/+page.server.js
- src/routes/(that conferences)/online/[state]/[year]/+page.svelte
- src/routes/(that conferences)/online/[state]/[year]/schedule/+page.svelte
- src/routes/(that conferences)/online/_components/Schedule.svelte
updating the live layout for wi/24 launch
> fix: launching online event for wi

- package-lock.json
- package.json
> updating posthog

- src/_components/activities/ActivityDetails.svelte
- src/_components/activities/List.svelte
- src/_elements/FeaturedActivity.svelte
- src/_elements/FeaturedActivityDetail.svelte
- src/routes/(admin my)/my/network/sponsors/+page.svelte
- src/routes/(admin sponsor)/sponsor-admin/my-network/+page.svelte
- src/routes/(admin)/admin/events/check-in/_components/_Order.svelte
- src/routes/(that conferences)/_components/schedule/Hero.svelte
Updated the website to display in the central time zone vs the browswers timezone.
> tz display as central

- src/routes/(admin my)/my/network/sponsors/+page.svelte
- src/routes/(admin sponsor)/sponsor-admin/my-network/+page.svelte
- src/routes/(admin)/admin/events/check-in/_components/_Order.svelte
imports for timezone were missing, now added.
> add missing tz imports

- src/routes/(admin my)/my/network/sponsors/+page.svelte
- src/routes/(admin sponsor)/sponsor-admin/my-network/+page.svelte
- src/routes/(admin)/admin/events/check-in/_components/_Order.svelte
updating the pages around the sponsor network to show more information as well as cleanup the timezone formatting issue.
> sponsor network

- src/routes/(root)/sponsors/_components/_PartnerCta.svelte
taking the sizing down for a longer cta.
> updates sponsor cta ui

- src/routes/(redirects)/camp/+page.server.js
- src/routes/(redirects)/family/+page.server.js
Updating the shortcut links to WI/2024
> update shortcut redirects

- src/routes/(that conferences)/online/[state]/[year]/+page.svelte
- src/routes/(that conferences)/online/_components/Live.svelte
enables the live stream iFrame
> loads up live

- src/routes/(that conferences)/online/[state]/[year]/+page.svelte
import was missing, no clue why the commit didn't take what was already on disk.
> merge issues

- src/routes/(that conferences)/online/_components/Schedule.svelte
- src/routes/(that conferences)/online/_components/schedule/List.svelte
updated the schedule and made a few visual updates
> updated online schedule

- src/routes/(root)/support/that-field-guide/+page.md
removed lanyanrd colors from field guide
> update field guide

- src/routes/(that conferences)/online/[state]/[year]/+page.svelte
Removing the iframe what was pointed at the live webinar.
> removing live webinar
